### ISSUE TITLE
parse pdf per page

### ISSUE THREAD

**Issue by harjedmor** [vaites/php-apache-tika#18]
is it possible to parse some page of pdf file to text?

**Comment by vaites** [comment]
@harjedmor is not possible with Apache Tika directly, because is not it's goal. You need to cut the PDF file first, and then use this library to extract the text. To do this, there are a few libraries on composer or tools like pdftoolbox or pdftk

[There's a trick](https://stackoverflow.com/questions/5824867/is-it-possible-to-extract-text-by-page-for-word-pdf-files-using-apache-tika/6271696#6271696) but I think that is not accurate or will change in the future without warning.
